name: ❄️ YAML Lint

on:
  pull_request:
    paths:
      - 'QUERIES.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yamllint
        uses: karancode/yamllint-github-action@v3.0.0
        with:
          yamllint_config_filepath: .yamllint
          yamllint_strict: false
          yamllint_comment: true